apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j.properties
            path: log4j.properties
      # - name: flink-config-volume
      #   hostPath:
      #     path: /data/flink/conf
      - name: flink-logs-volume
        hostPath:
          path: /data/flink/log
      containers:
      - name: jobmanager
        image: flink:1.9.1-scala_2.11
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/jobmanager.sh start;\
          while :;
          do
            if [[ -f $(find $FLINK_HOME/log -name '*jobmanager*.log' -print -quit) ]];
              then tail -f -n +1 $FLINK_HOME/log/*jobmanager*.log;
            fi;
          done"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: flink-logs-volume
          mountPath: /opt/flink/log
      # - name: flink-config-volume
      #   configMap:
      #     name: flink-config
      #     items:
      #     - key: flink-conf.yaml
      #       path: flink-conf.yaml
      #     - key: log4j.properties
      #       path: log4j.properties